/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as SqueezeRouteImport } from './routes/squeeze'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as LayoutTermsAndConditionsRouteImport } from './routes/_layout/terms-and-conditions'
import { Route as LayoutPrivacyPolicyRouteImport } from './routes/_layout/privacy-policy'
import { Route as LayoutHowItWorksRouteImport } from './routes/_layout/how-it-works'
import { Route as LayoutFrequentlyAskedQuestionsRouteImport } from './routes/_layout/frequently-asked-questions'
import { Route as LayoutContactUsRouteImport } from './routes/_layout/contact-us'
import { Route as LayoutAboutRouteImport } from './routes/_layout/about'
import { Route as AdminDashboardRouteRouteImport } from './routes/admin/dashboard/route'
import { Route as LayoutResourcesIndexRouteImport } from './routes/_layout/resources/index'
import { Route as AdminDashboardOverviewRouteImport } from './routes/admin/dashboard/overview'
import { Route as AdminDashboardCustomersRouteImport } from './routes/admin/dashboard/customers'
import { Route as AdminDashboardAppUsageRouteImport } from './routes/admin/dashboard/app-usage'
import { Route as LayoutResourcesResource_idRouteImport } from './routes/_layout/resources/$resource_id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SqueezeRoute = SqueezeRouteImport.update({
  id: '/squeeze',
  path: '/squeeze',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTermsAndConditionsRoute =
  LayoutTermsAndConditionsRouteImport.update({
    id: '/terms-and-conditions',
    path: '/terms-and-conditions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutPrivacyPolicyRoute = LayoutPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutHowItWorksRoute = LayoutHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutFrequentlyAskedQuestionsRoute =
  LayoutFrequentlyAskedQuestionsRouteImport.update({
    id: '/frequently-asked-questions',
    path: '/frequently-asked-questions',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutContactUsRoute = LayoutContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutAboutRoute = LayoutAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const AdminDashboardRouteRoute = AdminDashboardRouteRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutResourcesIndexRoute = LayoutResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const AdminDashboardOverviewRoute = AdminDashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardCustomersRoute = AdminDashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const AdminDashboardAppUsageRoute = AdminDashboardAppUsageRouteImport.update({
  id: '/app-usage',
  path: '/app-usage',
  getParentRoute: () => AdminDashboardRouteRoute,
} as any)
const LayoutResourcesResource_idRoute =
  LayoutResourcesResource_idRouteImport.update({
    id: '/resources/$resource_id',
    path: '/resources/$resource_id',
    getParentRoute: () => LayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/squeeze': typeof SqueezeRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/contact-us': typeof LayoutContactUsRoute
  '/frequently-asked-questions': typeof LayoutFrequentlyAskedQuestionsRoute
  '/how-it-works': typeof LayoutHowItWorksRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/terms-and-conditions': typeof LayoutTermsAndConditionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof LayoutIndexRoute
  '/resources/$resource_id': typeof LayoutResourcesResource_idRoute
  '/admin/dashboard/app-usage': typeof AdminDashboardAppUsageRoute
  '/admin/dashboard/customers': typeof AdminDashboardCustomersRoute
  '/admin/dashboard/overview': typeof AdminDashboardOverviewRoute
  '/resources': typeof LayoutResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/squeeze': typeof SqueezeRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/about': typeof LayoutAboutRoute
  '/contact-us': typeof LayoutContactUsRoute
  '/frequently-asked-questions': typeof LayoutFrequentlyAskedQuestionsRoute
  '/how-it-works': typeof LayoutHowItWorksRoute
  '/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/terms-and-conditions': typeof LayoutTermsAndConditionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof LayoutIndexRoute
  '/resources/$resource_id': typeof LayoutResourcesResource_idRoute
  '/admin/dashboard/app-usage': typeof AdminDashboardAppUsageRoute
  '/admin/dashboard/customers': typeof AdminDashboardCustomersRoute
  '/admin/dashboard/overview': typeof AdminDashboardOverviewRoute
  '/resources': typeof LayoutResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/squeeze': typeof SqueezeRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/dashboard': typeof AdminDashboardRouteRouteWithChildren
  '/_layout/about': typeof LayoutAboutRoute
  '/_layout/contact-us': typeof LayoutContactUsRoute
  '/_layout/frequently-asked-questions': typeof LayoutFrequentlyAskedQuestionsRoute
  '/_layout/how-it-works': typeof LayoutHowItWorksRoute
  '/_layout/privacy-policy': typeof LayoutPrivacyPolicyRoute
  '/_layout/terms-and-conditions': typeof LayoutTermsAndConditionsRoute
  '/admin/login': typeof AdminLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/resources/$resource_id': typeof LayoutResourcesResource_idRoute
  '/admin/dashboard/app-usage': typeof AdminDashboardAppUsageRoute
  '/admin/dashboard/customers': typeof AdminDashboardCustomersRoute
  '/admin/dashboard/overview': typeof AdminDashboardOverviewRoute
  '/_layout/resources/': typeof LayoutResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/squeeze'
    | '/waitlist'
    | '/admin/dashboard'
    | '/about'
    | '/contact-us'
    | '/frequently-asked-questions'
    | '/how-it-works'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/login'
    | '/'
    | '/resources/$resource_id'
    | '/admin/dashboard/app-usage'
    | '/admin/dashboard/customers'
    | '/admin/dashboard/overview'
    | '/resources'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/squeeze'
    | '/waitlist'
    | '/admin/dashboard'
    | '/about'
    | '/contact-us'
    | '/frequently-asked-questions'
    | '/how-it-works'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/admin/login'
    | '/'
    | '/resources/$resource_id'
    | '/admin/dashboard/app-usage'
    | '/admin/dashboard/customers'
    | '/admin/dashboard/overview'
    | '/resources'
  id:
    | '__root__'
    | '/_layout'
    | '/squeeze'
    | '/waitlist'
    | '/admin/dashboard'
    | '/_layout/about'
    | '/_layout/contact-us'
    | '/_layout/frequently-asked-questions'
    | '/_layout/how-it-works'
    | '/_layout/privacy-policy'
    | '/_layout/terms-and-conditions'
    | '/admin/login'
    | '/_layout/'
    | '/_layout/resources/$resource_id'
    | '/admin/dashboard/app-usage'
    | '/admin/dashboard/customers'
    | '/admin/dashboard/overview'
    | '/_layout/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  SqueezeRoute: typeof SqueezeRoute
  WaitlistRoute: typeof WaitlistRoute
  AdminDashboardRouteRoute: typeof AdminDashboardRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squeeze': {
      id: '/squeeze'
      path: '/squeeze'
      fullPath: '/squeeze'
      preLoaderRoute: typeof SqueezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/terms-and-conditions': {
      id: '/_layout/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof LayoutTermsAndConditionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/privacy-policy': {
      id: '/_layout/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof LayoutPrivacyPolicyRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/how-it-works': {
      id: '/_layout/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof LayoutHowItWorksRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/frequently-asked-questions': {
      id: '/_layout/frequently-asked-questions'
      path: '/frequently-asked-questions'
      fullPath: '/frequently-asked-questions'
      preLoaderRoute: typeof LayoutFrequentlyAskedQuestionsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/contact-us': {
      id: '/_layout/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof LayoutContactUsRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/about': {
      id: '/_layout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutAboutRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/resources/': {
      id: '/_layout/resources/'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/admin/dashboard/overview': {
      id: '/admin/dashboard/overview'
      path: '/overview'
      fullPath: '/admin/dashboard/overview'
      preLoaderRoute: typeof AdminDashboardOverviewRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/customers': {
      id: '/admin/dashboard/customers'
      path: '/customers'
      fullPath: '/admin/dashboard/customers'
      preLoaderRoute: typeof AdminDashboardCustomersRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/admin/dashboard/app-usage': {
      id: '/admin/dashboard/app-usage'
      path: '/app-usage'
      fullPath: '/admin/dashboard/app-usage'
      preLoaderRoute: typeof AdminDashboardAppUsageRouteImport
      parentRoute: typeof AdminDashboardRouteRoute
    }
    '/_layout/resources/$resource_id': {
      id: '/_layout/resources/$resource_id'
      path: '/resources/$resource_id'
      fullPath: '/resources/$resource_id'
      preLoaderRoute: typeof LayoutResourcesResource_idRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutAboutRoute: typeof LayoutAboutRoute
  LayoutContactUsRoute: typeof LayoutContactUsRoute
  LayoutFrequentlyAskedQuestionsRoute: typeof LayoutFrequentlyAskedQuestionsRoute
  LayoutHowItWorksRoute: typeof LayoutHowItWorksRoute
  LayoutPrivacyPolicyRoute: typeof LayoutPrivacyPolicyRoute
  LayoutTermsAndConditionsRoute: typeof LayoutTermsAndConditionsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutResourcesResource_idRoute: typeof LayoutResourcesResource_idRoute
  LayoutResourcesIndexRoute: typeof LayoutResourcesIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutAboutRoute: LayoutAboutRoute,
  LayoutContactUsRoute: LayoutContactUsRoute,
  LayoutFrequentlyAskedQuestionsRoute: LayoutFrequentlyAskedQuestionsRoute,
  LayoutHowItWorksRoute: LayoutHowItWorksRoute,
  LayoutPrivacyPolicyRoute: LayoutPrivacyPolicyRoute,
  LayoutTermsAndConditionsRoute: LayoutTermsAndConditionsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutResourcesResource_idRoute: LayoutResourcesResource_idRoute,
  LayoutResourcesIndexRoute: LayoutResourcesIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

interface AdminDashboardRouteRouteChildren {
  AdminDashboardAppUsageRoute: typeof AdminDashboardAppUsageRoute
  AdminDashboardCustomersRoute: typeof AdminDashboardCustomersRoute
  AdminDashboardOverviewRoute: typeof AdminDashboardOverviewRoute
}

const AdminDashboardRouteRouteChildren: AdminDashboardRouteRouteChildren = {
  AdminDashboardAppUsageRoute: AdminDashboardAppUsageRoute,
  AdminDashboardCustomersRoute: AdminDashboardCustomersRoute,
  AdminDashboardOverviewRoute: AdminDashboardOverviewRoute,
}

const AdminDashboardRouteRouteWithChildren =
  AdminDashboardRouteRoute._addFileChildren(AdminDashboardRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  SqueezeRoute: SqueezeRoute,
  WaitlistRoute: WaitlistRoute,
  AdminDashboardRouteRoute: AdminDashboardRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
